### ISSUE TITLE
Add where object to query and queryOne

### ISSUE THREAD

**Issue by hope-portal-services** [Elva/postgresql-query#3]
I'll likely end up doing this myself, but wanted to make the suggestion here. Happy to drop in a PR if it's something you might be interested in.

The configuration for `insert` and `update` queries is extremely useful, I find myself wanting the same functionality for a regular query.

ie:
- `db.queryWhere("table_name", { status: "active", name: "Joe" });`
- `db.queryOneWhere("table_name", { status: "active", name: "Joe" });`

While writing vanilla SQL is more flexible, the use case for a straight forward comparison object would be a nice addition.

**Comment by ltbits** [comment]
Depending on the use case WHERE clauses can get very complex and deep with many AND, OR combinations inside, but for simple scenarios like you described your solution might be useful. 

In my opinion though that type of query writing is better handled with ORMs like Sequelize.
